### ISSUE TITLE
Rendu exam

### ISSUE THREAD

**Issue by VivienCPNV** [VivienCPNV/GPR1-SocialNetwork#1]
Voici le rendu de l'examen @NicolasGlassey ,
Tout les test fonctionnent sauf pour le dernier.
Je pense que c'est un problème dut au test plus que au fonctionnement de mon projet, [détails ici](https://github.com/NicolasGlassey/GPR1-SocialNetwork/issues/3)
#[619cbb3](https://github.com/VivienCPNV/GPR1-SocialNetwork/commit/619cbb370e093d346b5615535a5e0c717c2e0e90)

**Comment by NicolasGlassey** [comment]
@VivienCPNV 

Bonjour Vivien,

J'ai bien pris en compte cette issue pour l'évaluation de votre examen.

Bonne suite de week-end !
